### ISSUE TITLE
trigger a error

### ISSUE THREAD

**Issue by aizuyan** [mplewis/src2png#6]
```
➜  src2png git:(master) node src/camera.js src/camera.js
/private/tmp/src2png/src/camera.js:28
async function startBrowser () {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
```

**Comment by mplewis** [comment]
Hi @aizuyan, what version of Node are you using?

**Comment by aizuyan** [comment]
@mplewis 
```
➜  src2png git:(master) node -v
v6.10.3
```

**Comment by aizuyan** [comment]
@mplewis 
Thanks for reminding.

version 8.5 is ok
```
➜  src2png git:(master) /usr/local/Cellar/node/8.5.0/bin/node -v
v8.5.0
```
