### ISSUE TITLE
Unexpected token function

### ISSUE THREAD

**Issue by nkuflk** [mplewis/src2png#7]
`node src/camera.js ../tornado/data.py`

I got error:
```/Users/flk/src2png/src/camera.js:28
async function startBrowser () {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:449:3```

**Comment by mplewis** [comment]
Hi @nkuflk, what version of Node are you using?

**Comment by nkuflk** [comment]
Hello, @mplewis my node version is `v6.2.0`

**Comment by mplewis** [comment]
You will need to upgrade to at least Node 7.10.1 to use this script. [That's the first version that supports async functions natively.](http://node.green/#ES2017-features-async-functions)

Hope this helps! Sorry for the inconvenience.

**Comment by nkuflk** [comment]
@mplewis Thanks a lot. That is helpful for me.
